# Other Matrix Operations

There are a variety of other matrix operations that are used within machine learning. Most of these are simpler than matrix multiplication, but regardless, they are important to know and use.

In [14]:
import numpy as np
import matplotlib.pyplot
from random import randint

## Transpose

In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**Problem:** Write a function that does the transpose. If you need to, try working it out by hand first and then coding.

In [6]:
def transpose(A):
    B = np.empty((A.shape[1], A.shape[0]))
    for i in range(A.shape[1]):
        for j in range(A.shape[0]):
            B[i][j] = A[j][i]
    return B

In [7]:
for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(*shape)
    assert np.allclose(A.T, transpose(A))
print('Success')

Success


**Problem:** Verify the first 3 properties of the matrix transpose listed in [Wikipedia](https://en.wikipedia.org/wiki/Transpose#Properties). Namely,

$$\begin{align}
\left(\mathbf {A} ^{\mathrm {T} }\right)^{\mathrm {T} }&=\mathbf {A} \quad  \\
\left(\mathbf {A} +\mathbf {B} \right)^{\mathrm {T} }&=\mathbf {A} ^{\mathrm {T} }+\mathbf {B} ^{\mathrm {T}} \\
\left(\mathbf {AB} \right)^{\mathrm {T} } &=\mathbf {B} ^{\mathrm {T} }\mathbf {A} ^{\mathrm {T} }
\end{align}$$

Use the built-in Numpy functions `A.dot(B)`, `A.T`, and `A + B` to demonstrate this numerically. Make sure you verify this for non-square matrices. Meaning ` A.shape[0] != A.shape[1] `.

In [12]:
for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(*shape)
    assert np.allclose(A.T.T, A)
print('Success')

for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(*shape)
    B = np.random.randn(*shape)
    assert np.allclose((A+B).T, A.T + B.T)
print('Success')

for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(shape[0], shape[1])
    B = np.random.randn(shape[1], shape[0])
    assert np.allclose((A.dot(B)).T, (B.T).dot(A.T))
print('Success')

Success
Success
Success


## Matrix-Vector Multiplication

A matrix times a vector is the same as a matrix times a matrix if the second matrix is a column,

In [13]:
A = np.arange(30).reshape((5, 6))
b = np.arange(6).reshape((6, 1))
print(A)
print(b)
print(A.dot(b))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[ 55]
 [145]
 [235]
 [325]
 [415]]


**Problem:** If I have a matrix $ A $ with shape `(N, M)` and multiply it by a vector $ x $. What shape must $ x $ be? What shape will $ A x $ be? Verify this numerically.

In [13]:
for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(shape[0], shape[1])
    B = np.random.randn(shape[1], 1)
    shape1 = (shape[0], 1)
    assert np.allclose(A.dot(B).shape, shape1)
print('Success')

Success


## Symmetric Matrices

Symmetric matrices are such that $ S = S^T $. We can make symmetric matrices by taking any square matrix $ A $ and doing $ S = A + A^T $.

**Problem:** Verify this numerically with a few randomly generated examples and then prove it analytically.

In [15]:
for i in range(10):
    n = randint(1, 100)
    A = np.random.randn(n, n)
    S = A + A.T
    assert np.allclose(S, S.T)
print('Success')

Success


You can also make symmetric matrices by doing $ S = A^T A $.

**Problem:** Verify this numerically with a few randomly generated examples and then prove it analytically.

In [16]:
for i in range(10):
    n = randint(1, 100)
    A = np.random.randn(n, n)
    S = (A.T).dot(A)
    assert np.allclose(S, S.T)
print('Success')

Success


Symmetric matrices like $ S = A^T A $ have a special property under multiplication. Namely for any vector $ z $ of the correct shape, $ z^T A^T A z \geq 0 $ regardless of the matrix $ A $.

**Problem:** Demonstrate this numerically by running random examples. If you know how, prove this analytically after.

In [17]:
for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(shape[0], shape[1])
    z = np.random.randn(shape[1], 1)
    assert (z.T).dot(A.T).dot(A).dot(z) >= 0
print('Success')

Success
